### ISSUE TITLE
JS error when accessing a page that does not include jQuery

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/aem-chrome-plugin#25]
@justinedelson reported that when the using AEM Chrome Plugin on a page that does not include jQuery a JS error is thrown.

**Comment by justinedelson** [comment]
Specifically, this is caused by https://github.com/Adobe-Consulting-Services/aem-chrome-plugin/blob/master/afCustomScript.js#L37

Interestingly... this error can be seen on _this_ page :)

**Comment by justinedelson** [comment]
Is there a reason why afCustomScript.js is loaded on every single webpage I go to? It seems like it should only run when enabled manually or on a pre-selected list of host/ports.
