### ISSUE TITLE
Fetch the log category from server

### ISSUE THREAD

**Issue by chetanmeh** [Adobe-Consulting-Services/aem-chrome-plugin#35]
Currently one needs to type in the log category names in the ad hoc log ui. This can be improved by fetching the log names and then generating the suggestion list

Logback has a JMX MBean which exposes the list of logger name. This can be accessed via Sling JMX ResourceProvider at http://localhost:4502/system/sling/monitoring/mbeans/ch/qos/logback/classic.tidy.2.json. Look for `LoggerList` attribute somewhere down in json. This can be used with some suggestor library (like used in Sling log Support UI) and can simplify log setting

**Comment by davidjgonzalez** [comment]
@chetanmeh This dumps "everything" log-gable back, right? WDYT about the LoggerNames tab that collects the LoggerNames for a particular request -- those can then be clicked on to be added to the ad-hoc tracer set. I thought this was a bit more handy in that this list is "naturally" scoped to the things someone cares about for that request.

The downside is they need to re-issue the request to get it logged.

Maybe we could add an auto-complete feature for type-aheads for this issue in the future?

![image](https://cloud.githubusercontent.com/assets/1451868/21126610/64ed98f6-c0bb-11e6-9471-b73c4a342d3d.png)

**Comment by chetanmeh** [comment]
> Maybe we could add an auto-complete feature for type-aheads for this issue in the future?

Yes we can use this for auto complete. LoggerNames was implemented later so meets the requirement now
