### ISSUE TITLE
Sling Log Tracer 1.0.2 supports AEM 6.0

### ISSUE THREAD

**Issue by chetanmeh** [Adobe-Consulting-Services/aem-chrome-plugin#38]
Now [Sling Log Tracer 1.0.2](https://repo1.maven.org/maven2/org/apache/sling/org.apache.sling.tracer/1.0.2/org.apache.sling.tracer-1.0.2.jar) has been released. This version support AEM 6.0 and has few new [enhancements](https://issues.apache.org/jira/browse/SLING/fixforversion/12335584) and bug fixes. We should update the links in plugin and site to refer to this new version

**Comment by davidjgonzalez** [comment]
Updated
