### ISSUE TITLE
Sling Tracer Logger Names do not appear to include every Logger

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/aem-chrome-plugin#44]
Example output: [1ef014c9-301b-4566-b3ea-ad9d3c578f4d.txt](https://github.com/Adobe-Consulting-Services/aem-chrome-plugin/files/717452/1ef014c9-301b-4566-b3ea-ad9d3c578f4d.txt)

Youll notice via RequestProgressLog, this request is handled by `com.adobe.granite.ui.clientlibs.impl.ClientLibraryProxyServlet` but in the LoggerNames list, this Servlet is not listed (and does have log statements)

I wanted to capture this here to record the issue in the context of the Plug-in, but expect well need a Sling issue to resolve.

**Comment by davidjgonzalez** [comment]
Oddly, even when I add `com.adobe.granite.ui.clientlibs.impl.ClientLibraryProxyServlet` as Tracer-set, i dont get logs for this class. 

I do see Sling Tracer header on the request to the AEM resources.. and the rest of data comes through. 

```
Sling-Tracer-Config:com.adobe.granite.ui.clientlibs.impl.ClientLibraryProxyServlet;level=DEBUG;caller=true,com.adobe.granite.ui.clientlibs.impl;level=TRACE;caller=true
Sling-Tracer-Record:true
```

**Comment by davidjgonzalez** [comment]
@chetanmeh  it looks like the happy-path for that request doesnt invoke any loggers; only when there is an issue w the requests (in my use case there are no issues).

I expected the LoggerNames to show the Servlet class as an option, though maybe thats not how Sling Log Tracer works (does the execution path have to invoke atleast 1 call to `log.xxx` in order to get added to the LoggerNames list? If so, it's probably worth adding a node to the Logger Names tab in the Plug-in that explains this.

**Comment by chetanmeh** [comment]
> does the execution path have to invoke atleast 1 call to log.xxx in order to get added to the LoggerNames list

Yes there has to be some callback from code to logger for the logger name to be pickedup. So at minimum 1 calls t log.xxx is required

**Comment by davidjgonzalez** [comment]
Ok - makes sense. I'll close this and update verbiage in plugin.  Thanks!
