### ISSUE TITLE
Debugger Issue?

### ISSUE THREAD

**Issue by twayne** [Adobe-Consulting-Services/aem-chrome-plugin#52]
I am unable to debug script on a toolbar button. The toolbar does not show up in the component hierarchy in the AEM Plugin debugger tab (the toolbar is a child of the guideRootPanel on my form) . Is this a bug, or am I doing something wrong?

<img width="516" alt="screen shot 2018-05-11 at 1 54 14 pm" src="https://user-images.githubusercontent.com/3106282/39941656-e0c33556-5522-11e8-8030-33e15ab1100c.png">

**Comment by davidjgonzalez** [comment]
@twayne sorry - im not very familiar w the forms portion of the plugin. And what version of AEM Forms are you on?


@gahuja1991 any idea?

**Comment by twayne** [comment]
I am on AEM 6.3 (OSGI).  Thanks.

**Comment by gahuja1991** [comment]
@twayne  
This looks like a bug. Working on this and will provide update on this.

**Comment by davidjgonzalez** [comment]
@gahuja1991 any update?

**Comment by gahuja1991** [comment]
@davidjgonzalez Sorry for the late reply. I've logged an issue for this. Will update the thread.

**Comment by davidjgonzalez** [comment]
I will have to cut a new release to make this available. I am traveling for work this week, but will try to find some time release hopefully!

**Comment by gahuja1991** [comment]
@davidjgonzalez  Were you able to provide a new release with this change?

**Comment by davidjgonzalez** [comment]
Its in 0.7.1 - thanks!
