### ISSUE TITLE
Enable Sling Log Tracer in AEM button never works in Chrome 72+

### ISSUE THREAD

**Issue by davidjgonzalez** [Adobe-Consulting-Services/aem-chrome-plugin#56]
I followed the first 4 steps in "How to use" section which are pretty straight forward.
But the plugin just won't work and I keep seeing this:

![image](https://user-images.githubusercontent.com/1451868/56165057-02ecf300-5fa0-11e9-912c-eb591c54ada5.png)

It appears that since Chrome 72, `extraHeader` must be passed into, else the referrer header is not set: https://stackoverflow.com/questions/54507977/cant-set-referer-or-cookie-header-in-chrome-extension-chrome-72/54507978#54507978

**Comment by mozzvinod** [comment]
It does not work. AEM version: 6.4.4
![image](https://user-images.githubusercontent.com/27548202/75323387-ca45c780-589a-11ea-817c-bcbaaa56abb4.png)

**Comment by davidjgonzalez** [comment]
@mozzvinod is your AEM instance on localhost:4502 and your admin account accessible via admin/admin ?  I havent installed 6.4.4 as its rather old, but it works on 6.5.2, 6.5.3 and AEM as a Cloud Service local quickstart jar.

**Comment by Pulkit-Jain89** [comment]
@davidjgonzalez  I am getting the same warning for a 6.5 set-up. 
https://github.com/Adobe-Consulting-Services/aem-chrome-plugin/issues/56#issue-433477019

Are there any additional steps need to be followed apart from the ones mentioned here- https://adobe-consulting-services.github.io/acs-aem-tools/aem-chrome-plugin/log-tracer/ ?

**Comment by davidjgonzalez** [comment]
@pulkitjain89 let me check - i have a 6.5.4.

Also, are you running on localhost? and is the admin user's credentials "admin:admin" ?

**Comment by davidjgonzalez** [comment]
hmm - just tried and works for me w/ Chrome Version 83.0.4103.61 (Official Build) (64-bit) and AEM 6.5.4.

If you're using anything "non-standard" its possible that Chrome cant make the HTTP request to Sling Log Tracer's OSGi Configuration Manager end-point to enable it. You can tweak things like if you're using a servlet context, the account that can access the OSGi console to get the Tracer results, etc. - you can even set it up for different hosts (incase your trying to debug a hosted instance). You DO need to have full access (ie. not blocked at Firewall) to the Sling Tracer endpoint under /system/console/... 


![image](https://user-images.githubusercontent.com/1451868/83776722-7f380f00-a656-11ea-8149-07886b394a77.png)

**Comment by Pulkit-Jain89** [comment]
@davidjgonzalez Thanks for your response! Only unusual piece could be the fact that i am using AEM J2EE server so a context "/lc" is added to access OSGI URLs (and added the same to the Servlet context as well). Will that make any difference?

**Comment by davidjgonzalez** [comment]
@pulkitjain89 absolutely - for that, open the plugins Options (tap the icon in the Chrome bar) and add your servlet context - otherwise the plugin will try to get the tracer info from /system/console/... rather than /lc/system/console/...

If this doesnt work, re-open the issue and let me know! Also, if you are using something other than admin:admin to access the osgi webconsole, you need to add that as well (remember to get the tracer results, tthe plugin makes an XHR to the sling tracer endpoint in the OSGi web console, so that XHR has to be able to have permissions to access that)

<img width="1271" alt="Screen Shot 2020-06-06 at 1 23 34 PM" src="https://user-images.githubusercontent.com/1451868/83950501-281e6f80-a7f9-11ea-80f5-30b5ef8c9079.png">

**Comment by Pulkit-Jain89** [comment]
Perfect @davidjgonzalez! Works fine after making the suggested changes.
Thanks!

**Comment by davidjgonzalez** [comment]
@pulkitjain89 super! Great to hear
