### ISSUE TITLE
Detect and deploy tracer bundle if required

### ISSUE THREAD

**Issue by chetanmeh** [Adobe-Consulting-Services/aem-chrome-plugin#8]
For the plugin to work we need [Apache Sling Tracer](https://sling.apache.org/documentation/bundles/log-tracers.html) to be present on server. To simplify setup for end user we can adapt following approach (based on suggestion by @justinedelson,  @michaelmarth - Suggested that similar approach is used in Sling IDE Tooling)
1. User opens the Dev Tools and selects the AEM Tab
2. AEM Plugin would then connect to server and check if required capabilities are met
3. If not then it displays a page which provides 2 sections. 
   - A - Provide manual steps on how to configure the stuff
   - B - Provides a button which when clicked connects to server and does the config
### Capability Check Logic
1. Check for Bundle - Make a GET request to `http://localhost:4502/system/console/bundles/org.apache.sling.tracer.json`. If bundle is present then json response is received. Otherwise 404
2. Check for required OSGi config - If bundle is present check if its enabled. For this GET request to `http://localhost:4502/system/console/configMgr/org.apache.sling.tracer.internal.LogTracer.json`. And check for `enabled.value=true` and `servletEnabled.value=true`. If both are enable that indicates Tracer is enabled for recording
### Deploying and configuring Tracer Bundle

To install the bundle a multi part post request to be sent to /system/console/bundle
1. action=install
2. bundlestart=true
3. bundlefile=<Bundle file>

The perform OSGi config via a POST to `/system/console/configMgr/org.apache.sling.tracer.internal.LogTracer` (details to be determined)

**Comment by davidjgonzalez** [comment]
1. Capability check logic
   - Low effort, high reward - we should definitely do this.
   - We should list out configured tracers as well (on Options screen)
     - This is useful since in options the tracerIds to target is configurable.
2. Deploying and configuring Tracer Bundle
   - I didn't see chrome extension APIs for reading a file directly from the Chrome extension itself (filesystem)
     - We could make a XHR for the Jar within the plugin and get the data that way
   - AEM referrer filter blocks the POST from the plugin (background.js)
     - Not sure if we can push the call to the actual content page to work around this.

**Comment by chetanmeh** [comment]
> We should list out configured tracers as well (on Options screen)

Tracer sets on server side are more of syntactic sugar. Instead we should allow user to configure a set of tracers set by default on option page and "expand" them client side while making the call to server

> I didn't see chrome extension APIs for reading a file directly from the Chrome extension itself 

Another option could be that we fetch it from Maven central. Need to be explored

**Comment by davidjgonzalez** [comment]
> I didn't see chrome extension APIs for reading a file directly from the Chrome extension itself
> Another option could be that we fetch it from Maven central. Need to be explored

Agree - i think the greater challenge will be POSTing it to AEM. I sort of like packaging it in Chrome since it makes it deployable even in offline scenarios (as long as you have the extension installed)

**Comment by davidjgonzalez** [comment]
Added Sling Tracer bundle checks along w configuration guidance. Closing this issue for now. 
We may want to create a follow up issue if we want to look into auto-deployment (though this may be dangerous if someone connects to an upper level environment and auto-deploys tracer accidentally)
